Added disable-legacy-macros option in configure.ac

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -878,6 +878,8 @@ GLIB_DIR
 DATADIR
 INSTMAN_TRUE
 INSTMAN_FALSE
+LEGACY_MACROS_TRUE
+LEGACY_MACROS_FALSE
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1482,6 +1484,7 @@ Optional Features:
   --enable-maintainer-mode  enable make rules and dependencies not useful
 			  (and sometimes confusing) to the casual installer
   --enable-install-man    Install man pages
+  --disable-legacy-macros Disable legacy macros
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -6405,13 +6408,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:6408: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:6411: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6411: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:6414: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6414: output\"" >&5)
+  (eval echo "\"\$as_me:6417: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -7521,7 +7524,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7524 "configure"' > conftest.$ac_ext
+  echo '#line 7527 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8933,11 +8936,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8936: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8939: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8940: \$? = $ac_status" >&5
+   echo "$as_me:8943: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9257,11 +9260,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9260: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9263: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9264: \$? = $ac_status" >&5
+   echo "$as_me:9267: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9362,11 +9365,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9365: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9368: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9369: \$? = $ac_status" >&5
+   echo "$as_me:9372: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9417,11 +9420,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9420: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9423: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9424: \$? = $ac_status" >&5
+   echo "$as_me:9427: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12178,7 +12181,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12181 "configure"
+#line 12184 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12278,7 +12281,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12281 "configure"
+#line 12284 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12915,6 +12918,39 @@ else
 fi
 
 
+# Check whether --enable-legacy-macros was given.
+if test "${enable_legacy_macros+set}" = set; then
+  enableval=$enable_legacy_macros; case "${enableval}" in
+       yes) legavy_macros=true ;;
+       no)  legacy_macros=false ;;
+       *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --disable-legacy-macros" >&5
+echo "$as_me: error: bad value ${enableval} for --disable-legacy-macros" >&2;}
+   { (exit 1); exit 1; }; } ;;
+     esac
+else
+  legacy_macros=true
+fi
+
+
+if test "x$legacy_macros" = "xfalse"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define LQR_DISABLE_LEGACY_MACROS
+_ACEOF
+
+fi
+
+
+
+if test x$legacy_macros = xtrue; then
+  LEGACY_MACROS_TRUE=
+  LEGACY_MACROS_FALSE='#'
+else
+  LEGACY_MACROS_TRUE='#'
+  LEGACY_MACROS_FALSE=
+fi
+
+
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -13051,6 +13087,13 @@ if test -z "${INSTMAN_TRUE}" && test -z "${INSTMAN_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"INSTMAN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"INSTMAN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${LEGACY_MACROS_TRUE}" && test -z "${LEGACY_MACROS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LEGACY_MACROS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LEGACY_MACROS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -13999,11 +14042,13 @@ GLIB_DIR!$GLIB_DIR$ac_delim
 DATADIR!$DATADIR$ac_delim
 INSTMAN_TRUE!$INSTMAN_TRUE$ac_delim
 INSTMAN_FALSE!$INSTMAN_FALSE$ac_delim
+LEGACY_MACROS_TRUE!$LEGACY_MACROS_TRUE$ac_delim
+LEGACY_MACROS_FALSE!$LEGACY_MACROS_FALSE$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 21; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 23; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
